
-- TABLA PREDIO
CREATE TABLE PREDIO 
(
  ID NUMBER NOT NULL 
, CHIP VARCHAR2(200) 
, MATRICULA_INMOBILIARIA VARCHAR2(200) 
, CEDULA_CATASTRAL VARCHAR2(200) 
, DIRECCION_PREDIO VARCHAR2(400) 
, TERRENO NUMBER 
, CONSTRUCCION NUMBER 
, TARIFA NUMBER 
, AJUSTE NUMBER 
, EXTENSION NUMBER 
);

CREATE SEQUENCE PREDIO_SEQ;

CREATE TRIGGER PREDIO_TRG 
BEFORE INSERT ON PREDIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PREDIO_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

ALTER TABLE PREDIO
ADD CONSTRAINT PREDIO_PK PRIMARY KEY 
(
  ID 
)
ENABLE;



-- TABLA PERSONA
CREATE TABLE PERSONA 
(
  ID NUMBER NOT NULL 
, NOMBRE VARCHAR2(400) 
, DIRECCION_NOTIFICACION VARCHAR2(200) 
, CODIGO_MUNICIPIO VARCHAR2(200) 
, CELULAR_CONTACTO VARCHAR2(20) 
, CORREO_CONTACTO VARCHAR2(200) 
, TELEFONO_CONTACTO VARCHAR2(20) NOT NULL 
, ID_PREDIO NUMBER 
, CONSTRAINT PERSONA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE PERSONA
ADD CONSTRAINT PERSONA_FK1 FOREIGN KEY
(
  ID_PREDIO 
)
REFERENCES PREDIO
(
  ID 
)
ENABLE;

CREATE SEQUENCE PERSONA_SEQ;

CREATE TRIGGER PERSONA_TRG 
BEFORE INSERT ON PERSONA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PERSONA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

-- TABLA PROMESA_COMPRA_VENTA
CREATE TABLE PROMESA_COMPRA_VENTA 
(
  ID NUMBER NOT NULL 
, VALOR_ACORDADO VARCHAR2(20) 
, FECHA_COMPRA_VENTA VARCHAR2(20) 
, ESTADO VARCHAR2(20) 
, ID_PREDIO NUMBER 
, ID_PERSONA NUMBER 
, CONSTRAINT PROMESA_COMPRA_VENTA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE PROMESA_COMPRA_VENTA
ADD CONSTRAINT PROMESA_COMPRA_VENTA_FK1 FOREIGN KEY
(
  ID_PREDIO 
)
REFERENCES PREDIO
(
  ID 
)
ENABLE;

ALTER TABLE PROMESA_COMPRA_VENTA
ADD CONSTRAINT PROMESA_COMPRA_VENTA_FK2 FOREIGN KEY
(
  ID_PERSONA 
)
REFERENCES PERSONA
(
  ID 
)
ENABLE;

CREATE SEQUENCE PROMESA_COMPRA_VENTA_SEQ;

CREATE TRIGGER PROMESA_COMPRA_VENTA_TRG 
BEFORE INSERT ON PROMESA_COMPRA_VENTA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PROMESA_COMPRA_VENTA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

